version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: apt-get update -y && apt-get install python-pip curl -y && pip install awscli
      - run:
          name: configure aws cli
          command: aws configure set aws_access_key_id $ACCESS_KEY && aws configure set aws_secret_access_key $SECRET_KEY
      - run:
          name: List all s3 buckets
          command: aws s3 ls
      - run:
          name: List all files of current directory
          command: ls -alh
      - run: 
          name: copy file to artifactory
          command: for file in $(ls *.tar.gz); do curl -uadmin:$ART_CERD -T $file "http://art1.xrepeater.com/zip-local/${file}"; done